### ISSUE TITLE
SDDM Theme

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nomad-plasma-look-and-feel#1]
@azubieta 

This is the mockup for the SDDM Theme:

![](http://i.imgur.com/PeNAKrs.png)

The design is basically the same as this: https://github.com/plasma-extensions/chromeo-lookandfeel/tree/master/sddm/chromeo _the differences are_:

- [x]  The top panel is colored #f5f5f5 .
- [x]  The comboboxes to select the session and the keyboard layout have borders (fill is: #f5f5f5 and border is: #c3c9d6).
- [x]  The line edits are the same color as the comboboxes when on normal state and on focus their border changes to #00acc1.
- ~~[ ]  There's a checkbox for SDDM to remember the last logged user. The checkbox can be an SVG; [it's the same that's in the Plasma theme](https://github.com/nomad-shell/nomad-plasma-look-and-feel/blob/master/plasma/nomad/widgets/checkmarks.svgz)~~
- [x]  There's a welcome message underneath the avatar.
- [x]  The text "Username" and "Password" should disappear when the fields are focused.
- [x]  There's a login button.
- [x]  The color of the text in dark is #212121.
- [x]  For the background the theme would use an overlay (#f5f5f5 90% opacity)  over the actual background (png/jpeg/etc.) and have the background blurred so that the user can change the background image from the SDDM KCM to match the background used in the desktop.

**Comment by azubieta** [comment]
@UriHerrera this is pretty much done, I'm just working on how to save the "remember last logged user" option. Please test it

**Comment by azubieta** [comment]
Saving settings is currently no supported by the SDDM according to its developers. I propose to hide the check "remember the last logged user" checkbox by the moment, and continue with the rest of the theme stuff.

**Comment by UriHerrera** [comment]
Let's close it for now.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/UM4c85s.png)

With comboboxes, input fields and button dimensions.

**Comment by UriHerrera** [comment]
With commit f4b8ef775642a0d016d398894e574305b902394c I'm getting this error:

![](http://i.imgur.com/pgEOu2N.png)
