### ISSUE TITLE
is the menu "selected item text overlay" fixed?

### ISSUE THREAD

**Issue by star-buck** [nomad-desktop/nomad-plasma-look-and-feel#10]
the one like visible here:
![nitrux_main](https://user-images.githubusercontent.com/840070/30667034-1a5b2210-9e4e-11e7-83dc-5431f88a5f9d.jpg)

**Comment by azubieta** [comment]
Yes was fixed, for the 1.3 release
Which one are you testing?
You can also apt update to be sure that you are using the latest version

**Comment by star-buck** [comment]
Okay, then simply close that ticket again. :)
