### ISSUE TITLE
Fix default wallpaper theme

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nomad-plasma-look-and-feel#11]
The property "defaultWallpaperTheme" should be a wallpaper theme name not "2560x1080".

https://github.com/nomad-desktop/nomad-plasma-look-and-feel/blob/830b4098839b5d26b0a32e58ae33b8d3731fedb2/plasma/nomad/metadata.desktop#L20

https://github.com/nomad-desktop/nomad-plasma-look-and-feel/blob/830b4098839b5d26b0a32e58ae33b8d3731fedb2/plasma/nomad-dark/metadata.desktop#L20

**Comment by UriHerrera** [comment]
Fix by https://github.com/nomad-desktop/nomad-plasma-look-and-feel/commit/5953f0b27be80fbc7ca678a70e9b864d579f9dfb
