### ISSUE TITLE
Restore In Application menu

### ISSUE THREAD

**Issue by AlpNek** [nomad-desktop/nomad-plasma-look-and-feel#21]
I am using Nitrux and love it. But on wayland the global menu disappears. What config can i edit to restore the menu to each window (In Application)?

Thx.

**Comment by UriHerrera** [comment]
Thanks for using Nitrux!. We haven't moved to use Wayland as the default windowing system yet but if you find bugs with the global menu under Wayland it's better to let KDE developers know about this issue 

Here's the [bug report about it](https://bugs.kde.org/show_bug.cgi?id=385880).

**Comment by AlpNek** [comment]
Thanks Uri. I added my comment to the bug report for KDE Devs.
