### ISSUE TITLE
Issues in Nomad Kvantum Theme

### ISSUE THREAD

**Issue by frozenxuan** [nomad-desktop/nomad-plasma-look-and-feel#31]
Reported here because 'Issues' card is missing from  'Nomad Kvantum Theme' project board.
1. In Dolphin if 'Show Space Information' is checked, the progress bar messed with the text. The text should be wholely placed in the bar, but now a part of the text is outside of the bar and is barely visible due to the white text color.
2. Some dropdowns are partially transparent thus messed with other elements in the background (the picture attached is shown with 'System Setting', but I observed the same issue in 'Spectacle' as well)

**Comment by frozenxuan** [comment]
![screenshot_20180503_204132](https://user-images.githubusercontent.com/6898228/39578168-0333c532-4f16-11e8-9646-24832a0b7159.png)
![screenshot_20180503_204108](https://user-images.githubusercontent.com/6898228/39578171-058587e4-4f16-11e8-9efe-8c07fe31d722.png)

**Comment by UriHerrera** [comment]
Confirmed. Kvantum 0.10.7 breaks the theme.

**Comment by UriHerrera** [comment]
Fixed in https://github.com/nomad-desktop/nomad-kvantum-theme/commit/e690d426b37700f721ca9c77b605ff69de6093d9
