### ISSUE TITLE
Backport media player controls from Breeze lockscreen

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nomad-plasma-look-and-feel#8]
KDE Devs added media player controls to the Breeze lockscreen a while back, it would be nice to add them to ours too.
- [ ] Add media player controls to Lock screen.

@azubieta Controls would be located below the "Unlock" button using the same spacing that there is between the clock and the button.

**Comment by anupam-git** [comment]
Closing this issue as the media controls are backported and working.

Re-open if necessary.
